# Generated by Django 4.1.4 on 2023-01-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_post_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user_name",
            field=models.CharField(default=256, max_length=256),
        ),
    ]
